wireplumber.settings = {
  bluetooth.autoswitch-to-headset-profile = false
}

monitor.bluez.properties = {
  bluez5.auto-connect = [ a2dp_sink hsp_hs hfp_hf ]
  bluez5.headset-roles = [ hsp_hs hfp_hf ]
}
