monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.*"
      }
    ]
    actions = {
      update-props = {
        node.description = "Ограниченный выход"
        # Лимит громкости (1.0 = 100%)
        volume.max = 1.0
      }
    }
  }
]
